config/routes.rb
Rails.application.routes.draw do

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]  
  end

  devise_for :users
  resources :users
  
  root to: 'wikis#index'

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :wikis, through: :collaborators
  has_many :collaborators
  has_many :wikis

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  after_initialize :default_role

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def admin?
    role == 'admin'
  end


  private

  def default_role
    self.role ||= 'standard'
  end

  


  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :users, through: :collaborators
  has_many :collaborators

  validates :title, presence: true

  def private_wiki?
    is_private == true
  end

  def public_wiki?
    is_private == false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  respond_to :html, :js


  
  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken],
      plan: 'blocipedia premium'
    )
 
    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 1500,
      #name: 'premium membership',
      description: "Blocipedia Membership - #{current_user.email}",
      currency: 'gbp'
    )

    current_user.subid = customer.subscriptions['data'][0].id
    current_user.stripeid = customer.id
    current_user.role = :premium
    current_user.save

    redirect_to root_path # or wherever
    flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
 
 # Stripe will send back CardErrors, with friendly messages
 # when something goes wrong.
 # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def new

    if current_user.role == 'premium'
      redirect_to root_path
      flash[:error] = "You are already a premium member"
    end

    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Membership - #{current_user.name}",
      amount: 1500
    }
  end

  def downgrade
    @user = current_user

    Stripe.api_key = "#{ Rails.configuration.stripe[:secret_key] }"

    customer = Stripe::Customer.retrieve(id: @user.stripeid)
    customer.subscriptions.retrieve(@user.subid).delete

    @user.update_attributes(stripeid: nil, subid: nil)

    current_user.role = :standard
    current_user.save

    redirect_to root_path # or wherever
    flash[:success] = "Sorry to see you go"
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :find_wiki

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

      if @collaborator.save
        flash[:notice] = "Collaborator added."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:error] = "There was a problem adding a collaborator. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
        flash[:notice] = "Collaborator removed"
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:error] = "There was an error. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
  end

  private 

  def find_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.where(is_private: false)
    @personal_wikis = policy_scope(Wiki)
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.users
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki post saved."
      redirect_to @wiki
    else
      flash[:error] = "Error, wiki post not saved."
      redirect_to new_wiki_path
    end

  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all.select {|user| user != current_user }
    @collaborators = @wiki.users
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki, please try again"
      render :edit
    end

  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to root_path
    else
      flash[:error] = "There was an error deleting this wiki post"
      render :show
    end
    
  end
  
end

private

def wiki_params
  params.require(:wiki).permit(:title, :body, :is_private)
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end

end

app/views/charges/new.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey("<%= Rails.configuration.stripe[:publishable_key] %>");

  var stripeResponseHandler = function(status, response) {
    var $form = $('#payment-form');

    if (response.error) {
      // Show the errors on the form
      $form.find('.payment-errors').text(response.error.message);
      $form.find('button').prop('disabled', false);
    } else {
      // response contains id and card, which contains additional card details
      var token = response.id;
      // Insert the token into the form so it gets submitted to the server
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      // and submit
      $form.get(0).submit();
    }
  };
  
  jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});
</script>

<%= form_tag charges_path, id: 'payment-form' do %>
  <h4>custom form</h4>
  <p>Upgrade to premium membership for $15</p>
  <span class="payment-errors"></span>
  <%= label_tag("Card Number") %>
   <%= text_field_tag :card_number, nil, name: nil, :placeholder => "Card Number", :data => {:stripe => 'number'} %>
   <%= text_field_tag :cvc, nil, name: nil, :placeholder => "CVC", :size => 4, :data => {:stripe => 'cvc'} %>
   <%= text_field_tag :expmonth, nil, name: nil, :placeholder => "MM", :size => 2, :data => {:stripe => 'exp-month'} %>
   <span>/</span>
   <%= text_field_tag :expyear, nil, name: nil, :placeholder => "YY", :size => 2, :data => {:stripe => 'exp-year'} %>

   <%= button_tag :submit, name: nil %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-no-turbolink\>
    <header>
      <nav class="left">
        <% if current_user %>
          <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
          <%= link_to "New wiki post", new_wiki_path %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
        <% end %>
        <% if current_user && current_user.standard? %>
          <%= link_to "Upgrade", new_charge_path %>
        <% end %>

        <% if current_user %>
          <%= link_to "My Account", current_user %>
          <p><%= current_user.role %> user accout</p>
        <% end %>
      </nav>
    </header>

    <main>
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% elsif flash[:error] %>
        <p class="error"><%= flash[:error] %></p>
      <% end %>

      <%= yield %>
    </main>

  </body>
</html>

app/views/users/show.html.erb
<h1><%= current_user.name.capitalize %></h1>

<h2><%= current_user.role.capitalize %> Member</h2>
<p><%= current_user.subid %></p>
<p><%= current_user.stripeid %></p>

<% if current_user.premium? %>
  <%= link_to "Cancel Subscription", downgrade_path %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <% if current_user.premium? %>
    <%= f.label 'Private wiki' %>
    <%= f.check_box :is_private %>
  <% end %>

  <%= f.submit "Save" %>

<% end %>

app/views/wikis/edit.html.erb
<h1>Edit wiki</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>

<% if @wiki.is_private? %>
  <div class="current-collaborators">
    <h2>Current Collaborators</h2>
    <%= @collaborators.each do |collaborator| %>
      <div class="collabotator">
        <%= collaborator.email %>
        <%= link_to "Remove collaborator", wiki_collaborator_path(@wiki, collaborator), method: :delete %>
      </div>  
    <% end %>
  </div>

  <div class="add-collaborators">
    <h2>Add Collaborators</h2>
    <% @users.each do |user| %>
      <% unless @wiki.users.include?(user) %>
        <div class="add-collaborator email"><%= user.email %></div>
        <div class="add-collaborator userid"><%= user.id %></div>
        <div class="add-collaborator link">
          <%= link_to "Add as collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post %>
        </div>
    <% end %>
    <% end %>
  </div>
<% end %>

app/views/wikis/index.html.erb
<h1>Welcome to Blocipedia</h1>

<section class="main">
  <%= @wikis.each do |wiki| %>
    
    <div class="wiki-index">
      <%= link_to wiki.title, wiki_path(wiki.id) %>
      <% if policy(wiki).update? %>
        <span class="edit"><%= link_to "edit", edit_wiki_path(wiki.id) %></span>
      <% end %>
    </div>

  <% end %>
</section>

<% if current_user %>
  <h1>My Wikis</h1>

  <% @personal_wikis.each do |wiki| %>
    <div class="my-wikis">
      <%= link_to wiki.title, wiki_path(wiki.id) %>
      <% if policy(wiki).update? %>
        <span class="edit"><%= link_to "edit", edit_wiki_path(wiki.id) %></span>
      <% end %>
    </div>

  <% end %>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki Post</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>
  

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<p><%= markdown_to_html @wiki.body %></p>
<p>Privicy: <%= @wiki.is_private %></p>

<%= @collaborators.each do |c| %>
	<div class="collabotator">
  	<%= c.email %>
	</div>  
<% end %>

<div class="wiki-actions">
  <%= link_to "delete", [@wiki], method: :delete %>
  <%= link_to "edit", edit_wiki_path %>
</div>